import type {
  CitationSourceSpan,
  ContextCitationSpan,
  ContextItem,
  ContextPackageResponse,
  GraphEdge,
  GraphNode,
  GraphNodeWeightDiagnostics,
  GraphProjectionGroupDiagnostics,
  GraphResponse,
  GraphRetrievalStepResponse,
  GrayTraversalObservationBudgetState,
  RetrievalGrayZoneDecision,
  RetrievalAgentOperatingEnvelope,
  RetrievalSupportRefs,
  RetrievalTraceDiagnostics,
  RetrievalTraceStepsResponse,
  RetrievalTraversalState,
} from "@course-kg/shared";

export const CONTRACT_HASH = "a".repeat(64);

export function makeAgentOperatingEnvelope(
  overrides: Partial<RetrievalAgentOperatingEnvelope> = {},
): RetrievalAgentOperatingEnvelope {
  return {
    agent_coarse_initial_budget: 8,
    agent_coarse_total_budget: 12,
    agent_coarse_top_k: 8,
    agent_mid_per_coarse_budget: 4,
    agent_coarse_drilldown_mid_initial_budget: 8,
    agent_mid_initial_budget: 8,
    agent_mid_top_k: 12,
    agent_chunk_per_mid_budget: 3,
    agent_chunk_initial_budget: 8,
    agent_chunk_top_k: 12,
    max_depth_per_layer: 4,
    max_labels_per_node: 8,
    max_edge_reuse: 2,
    max_cycle_reward_per_path: 0.25,
    cycle_reward_distance_threshold: 0.5,
    path_distance_green_threshold: 0.5,
    path_distance_gray_threshold: 1,
    path_distance_hard_threshold: 2,
    gray_zone_rule_protocol_version: "deterministic_support_progress_v1",
    gray_zone_rule_protocol_hash: CONTRACT_HASH,
    gray_zone_observation_cadence: 1,
    traversal_observation_budget: 64,
    gray_zone_model_call_budget: 0,
    query_facet_posterior_enabled: true,
    query_facet_posterior_observation_budget: 64,
    query_facet_posterior_round_budget: 2,
    query_facet_posterior_convergence_epsilon: 0.02,
    query_facet_posterior_llm_sample_budget: 0,
    candidate_pool_dedupe_budget: 256,
    structure_restore_per_chunk_budget: 3,
    structure_restore_budget: 3,
    context_package_token_budget: 4096,
    context_path_summary_budget: 512,
    planning_round_budget: 4,
    max_typed_actions_per_round: 8,
    repair_round_budget: 2,
    verification_budget: 2,
    allowed_relation_types: [
      "dense_semantic",
      "dense_cross_document_bridge",
      "dense_cross_language_bridge",
    ],
    required_restore_modes: ["previous_next", "parent_structure", "bridge_chunks"],
    ...overrides,
  };
}

export function makeTraceDiagnostics(
  overrides: Partial<RetrievalTraceDiagnostics> = {},
): RetrievalTraceDiagnostics {
  return {
    retrieval_granularity: "mid",
    repair_gray_zone_decision_authority: false,
    repair_gray_zone_model_call_count: 0,
    runtime_settings_hash: "9".repeat(64),
    gray_zone_runtime_settings_identity_protocol_version:
      "gray_zone_runtime_settings_identity_v1",
    gray_zone_runtime_settings_hash: "8".repeat(64),
    gray_zone_query_facet_protocol_version:
      "deterministic_gray_query_tokenizer_v1",
    gray_zone_query_facet_hash: "5".repeat(64),
    gray_zone_external_routing_packet_used: false,
    gray_zone_request_scoped_budget_in_identity: false,
    query_facet_posterior_calibration: {
      protocol_version: "query_facet_posterior_calibration_v1",
      protocol_hash: CONTRACT_HASH,
      enabled: true,
      query_facet_packet_hash: CONTRACT_HASH,
      required_facets: [],
      prior: {},
      posterior: {},
      alias_posterior: {},
      rounds: [],
      observations: [],
      round_budget: 2,
      rounds_used: 0,
      observation_budget: 64,
      observations_used: 0,
      convergence_epsilon: 0.02,
      converged: false,
      stop_reason: "disabled_no_required_facets",
      llm_sample_budget: 0,
      model_call_count: 0,
      is_evidence: false,
      citation_authority: false,
      graph_mutation_authority: false,
      gray_zone_decision_authority: false,
      posterior_used_as_numeric_query_relevance: false,
      posterior_used_only_within_equal_uncovered_count: true,
      calibration_hash: CONTRACT_HASH,
    },
    agent_operating_envelope: makeAgentOperatingEnvelope(),
    agent_operating_envelope_hash: "7".repeat(64),
    effective_traversal_protocol_hash: "6".repeat(64),
    scores_json_retired_as_primary_audit: true,
    ...overrides,
  };
}

export function makeSourceSpan(overrides: Partial<CitationSourceSpan> = {}): CitationSourceSpan {
  return {
    contract_version: "raw_chunk_source_span_v1",
    document_version_id: "document-version:fixture",
    chunk_id: "chunk:fixture",
    source_path: "fixture.md",
    source_checksum: CONTRACT_HASH,
    logical_source_path: "fixture.md",
    source_snapshot_verification: {
      protocol_version: "immutable_source_snapshot_v1",
      final_open_protocol_version: "posix_openat_nofollow_fstat_v1",
      storage_path: "fixture.md",
      checksum: CONTRACT_HASH,
      verified: true,
      size_bytes: 128,
    },
    chunk_text_hash_protocol_version: "chunk_text_sha256_normalized_v1",
    chunk_text_hash: CONTRACT_HASH,
    raw_span_text_hash_protocol_version: "raw_span_text_sha256_v1",
    raw_span_text_hash: CONTRACT_HASH,
    char_span: [0, 10],
    raw_chunk_char_span: [0, 10],
    page_range: [1, 1],
    section_path: [],
    structure_path: [],
    structure_node_ids: [],
    content_clipped: false,
    content_token_count: 4,
    ...overrides,
  };
}

export function makeContextItem(overrides: Partial<ContextItem> = {}): ContextItem {
  const sourceSpan = makeSourceSpan();
  return {
    contract_kind: "context_item",
    chunk_id: sourceSpan.chunk_id,
    document_title: "Fixture document",
    source_path: sourceSpan.source_path,
    content: "Fixture evidence text.",
    snippet: "Fixture evidence text.",
    metadata: {
      source_path: sourceSpan.source_path,
      logical_source_path: sourceSpan.logical_source_path,
      section_path: [],
      structure_path: [],
      structure_node_ids: [],
      page_range: sourceSpan.page_range,
      char_span: sourceSpan.char_span,
      source_span: sourceSpan,
      structure_closure: {
        same_page_region_node_ids: [],
        table_formula_caption_node_ids: [],
        code_block_node_ids: [],
        bridge_chunk_ids: [],
        same_page_region: [],
        table_formula_caption: [],
        code_blocks: [],
      },
      why_selected: {
        roles: ["hit"],
        path_edge_ids: [],
        covered_facets: [],
        reason: "hit",
        reached_by_paths: [],
        query_facets: [],
        evidence_roles: [],
        graph_paths: [],
        graph_path_chunks: [],
        convergence_score: 0,
        node_visit_count: 0,
        distinct_parent_count: 0,
        distinct_path_count: 0,
        distinct_edge_type_count: 0,
        parent_node_ids: [],
        support_chunk_union: [],
      },
      dedupe_key: `${sourceSpan.chunk_id}:[0,10]`,
      role: "hit",
      content_clipped: false,
      content_token_count: 4,
      original_token_count: 4,
      raw_chunk_char_span: [0, 10],
      context_package_id: "package:fixture",
    },
    ...overrides,
  };
}

export function makeContextCitationSpan(
  overrides: Partial<ContextCitationSpan> = {},
): ContextCitationSpan {
  const sourceSpan = makeSourceSpan();
  return {
    contract_kind: "citation_span",
    document_id: "document:fixture",
    document_title: "Fixture document",
    source_path: sourceSpan.source_path,
    logical_source_path: sourceSpan.logical_source_path,
    section_path: [],
    structure_path: [],
    structure_node_ids: [],
    structure_closure: {
      same_page_region_node_ids: [],
      table_formula_caption_node_ids: [],
      code_block_node_ids: [],
      bridge_chunk_ids: [],
      same_page_region: [],
      table_formula_caption: [],
      code_blocks: [],
    },
    source_span: sourceSpan,
    ...overrides,
  };
}

const emptyCounts: GraphResponse["counts"] = {
  chunks: 0,
  active_chunks: 0,
  structure_nodes: 0,
  structure_edges: 0,
  structure_mappings: 0,
  chunk_relation_edges: 0,
  rq_prefixes: 0,
  rq_prefix_memberships: 0,
  rq_prefix_pair_diagnostics: 0,
  rq_relation_edges: 0,
  mid_concepts: 0,
  mid_concept_edges: 0,
  mid_concept_memberships: 0,
  coarse_concepts: 0,
  coarse_concept_edges: 0,
  coarse_concept_memberships: 0,
};

const emptyNodeMetadata: GraphNode["metadata"] = {
  rq_path: [],
  rq_path_prefix: [],
  representative_chunk_ids: [],
  support_chunk_ids: [],
  bridge_chunk_ids: [],
};

const emptyNodeWeightDiagnostics: GraphNodeWeightDiagnostics = {
  normalization_scope: "mid_concept_state",
  cross_layer_comparison_allowed: false,
  query_relevance: false,
  model_call_count: 0,
  component_weights: {},
  components: {},
  membership_role_mass_distribution: {},
};

type MidNode = Extract<GraphNode, { contract_kind: "mid_concept_node" }>;
type CoarseNode = Extract<GraphNode, { contract_kind: "coarse_concept_node" }>;
type ChunkNode = Extract<GraphNode, { contract_kind: "chunk_node" }>;
type RqNode = Extract<GraphNode, { contract_kind: "rq_prefix_node" }>;

export function makeMidConceptNode(id: string, overrides: Partial<MidNode> = {}): MidNode {
  return {
    contract_kind: "mid_concept_node",
    id,
    label: id,
    name: id,
    type: "mid_concept",
    category: "mid_concept",
    raw_node_weight: 1,
    node_weight: 1,
    node_weight_normalization_scope: "mid_concept_state",
    node_weight_diagnostics: { ...emptyNodeWeightDiagnostics },
    support_chunk_ids: [],
    support_active_chunk_ids: [],
    support_rq_prefix_ids: [],
    representative_chunk_ids: [],
    section_path: [],
    metadata: { ...emptyNodeMetadata },
    ...overrides,
  };
}

export function makeCoarseConceptNode(id: string, overrides: Partial<CoarseNode> = {}): CoarseNode {
  return {
    contract_kind: "coarse_concept_node",
    id,
    label: id,
    name: id,
    type: "coarse_concept",
    category: "coarse_concept",
    raw_node_weight: 1,
    node_weight: 1,
    node_weight_normalization_scope: "coarse_concept_state",
    node_weight_diagnostics: {
      ...emptyNodeWeightDiagnostics,
      normalization_scope: "coarse_concept_state",
    },
    support_chunk_ids: [],
    support_active_chunk_ids: [],
    support_rq_prefix_ids: [],
    representative_chunk_ids: [],
    included_mid_concept_ids: [],
    boundary_mid_concept_ids: [],
    bridge_mid_concept_ids: [],
    outlier_mid_concept_ids: [],
    low_confidence_mid_concept_ids: [],
    all_mid_concept_ids: [],
    section_path: [],
    metadata: { ...emptyNodeMetadata },
    ...overrides,
  };
}

export function makeChunkNode(id: string, overrides: Partial<ChunkNode> = {}): ChunkNode {
  return {
    contract_kind: "chunk_node",
    id,
    label: id,
    name: id,
    type: "chunk",
    category: "chunk",
    support_chunk_ids: [],
    support_active_chunk_ids: [],
    support_rq_prefix_ids: [],
    representative_chunk_ids: [],
    section_path: [],
    metadata: { ...emptyNodeMetadata },
    ...overrides,
  };
}

export function makeRqPrefixNode(id: string, overrides: Partial<RqNode> = {}): RqNode {
  return {
    contract_kind: "rq_prefix_node",
    id,
    label: id,
    name: id,
    type: "rq_prefix",
    category: "rq_prefix",
    support_chunk_ids: [],
    support_active_chunk_ids: [],
    support_rq_prefix_ids: [],
    representative_chunk_ids: [],
    section_path: [],
    metadata: { ...emptyNodeMetadata },
    ...overrides,
  };
}

type RelationEdge = Extract<GraphEdge, { contract_kind: "chunk_relation_edge" }>;
type ProjectionEdge = Extract<GraphEdge, { contract_kind: "concept_projection_edge" }>;

export function makeRelationEdge(source: string, target: string, overrides: Partial<RelationEdge> = {}): RelationEdge {
  return {
    contract_kind: "chunk_relation_edge",
    id: `${source}->${target}`,
    source,
    target,
    type: "concept_relation",
    category: "concept_relation",
    support_chunk_ids: [],
    support_chunk_edge_ids: [],
    support_mid_edge_ids: [],
    support_mid_concept_ids: [],
    support_rq_prefix_ids: [],
    metadata: {
      candidate_channels: [],
      top_alternative_prefix_ids: [],
      rq_path: [],
      support_chunk_ids_sample: [],
      support_chunk_edge_ids_sample: [],
    },
    ...overrides,
  };
}

export function makeProjectionEdge(
  source: string,
  target: string,
  overrides: Partial<ProjectionEdge> = {},
): ProjectionEdge {
  const bottomEdgeId = "chunk-edge:fixture";
  const distribution = { count: 1, min: 0.2, max: 0.2, mean: 0.2, population_std: 0 };
  return {
    contract_kind: "concept_projection_edge",
    id: `${source}->${target}`,
    source,
    target,
    type: "projected_dense_semantic",
    category: "projected_dense_semantic",
    weight: 0.8,
    distance: 0.22,
    projected_distance_raw: 0.25,
    projected_strength_raw: 0.78,
    raw_strength_summary: {
      aggregation_protocol_version: "membership_weighted_bottom_support_q15_log_mass_v1",
      q15_bottom_distance: 0.2,
      support_membership_mass: 0.72,
      support_mid_edge_count: 0,
      support_chunk_edge_count: 1,
      bottom_distance_distribution: distribution,
      membership_product_distribution: {
        count: 1,
        min: 0.72,
        max: 0.72,
        mean: 0.72,
        population_std: 0,
      },
      dominant_bottom_edge_type: "dense_semantic",
      bottom_edge_type_membership_mass: {
        dense_semantic: 0.72,
        dense_cross_document_bridge: 0,
        dense_cross_language_bridge: 0,
      },
      contribution_facts_hash: CONTRACT_HASH,
      edge_distance_protocol: "edge_distance_log_calibrated_strength_v2",
    },
    edge_projection_protocol_hash: CONTRACT_HASH,
    projection_normalization: {
      normalization: "layer_edge_type_winsorized_minmax_v1",
      protocol_version: "layer_edge_type_winsorized_minmax_v1",
      edge_projection_protocol_version: "membership_q15_layer_type_calibrated_v3",
      edge_projection_protocol_hash: CONTRACT_HASH,
      layer: "mid",
      edge_type: "projected_dense_semantic",
      scope: "layer_plus_edge_type",
      params: { lower_quantile: 0.05, upper_quantile: 0.95, min_span: 0.001, strength_floor: 0.000001 },
      sample_count: 1,
      lower_quantile_value: 0.78,
      upper_quantile_value: 0.78,
      quantile_span: 0,
      fallback: "single_sample",
      calibration_applied: false,
      raw_strength_distribution: distribution,
      calibrated_strength_distribution: distribution,
      calibrated_distance_distribution: distribution,
      cross_type_raw_comparison_allowed: false,
      model_call_count: 0,
      stats_hash: CONTRACT_HASH,
      support_edge_count: 1,
      support_mid_edge_count: 0,
      support_chunk_edge_count: 1,
      support_membership_mass: 0.72,
    },
    diagnostics: {
      edge_projection_protocol: "membership_q15_layer_type_calibrated_v3",
      edge_projection_protocol_hash: CONTRACT_HASH,
      aggregation_protocol_version: "membership_weighted_bottom_support_q15_log_mass_v1",
      calibration_protocol_version: "layer_edge_type_winsorized_minmax_v1",
      source_algorithm: "membership_weighted_bottom_edge_projection",
      support_rq_prefix_ids: ["rq:fixture"],
      support_mid_edge_count: 0,
      support_chunk_edge_count: 1,
      support_contribution_count: 1,
      support_membership_mass: 0.72,
      support_contributions: [
        {
          bottom_chunk_edge_id: bottomEdgeId,
          source_chunk_id: "chunk:source",
          target_chunk_id: "chunk:target",
          bottom_edge_type: "dense_semantic",
          bottom_distance: 0.2,
          source_membership_score: 0.9,
          target_membership_score: 0.8,
          membership_product: 0.72,
          orientation: "source_scope_to_target_scope",
          assignment_protocol_version: "scope_key_chunk_business_assignment_v1",
          bottom_edge_fact_hash: CONTRACT_HASH,
        },
      ],
      support_contributions_complete: true,
      contribution_facts_hash: CONTRACT_HASH,
      dominant_bottom_edge_type: "dense_semantic",
      support_edge_types: {
        dense_semantic: 1,
        dense_cross_document_bridge: 0,
        dense_cross_language_bridge: 0,
      },
      semantic_uncertain: false,
      crossing_rq_boundary: false,
      gray_predicates: {
        protocol_version: "projected_gray_predicates_support_rollup_v1",
        protocol_hash: CONTRACT_HASH,
        semantic_uncertain: false,
        crossing_rq_boundary: false,
        support_edge_count: 1,
        semantic_uncertain_support_count: 0,
        rq_boundary_support_count: 0,
        semantic_uncertain_support_edge_ids: [],
        rq_boundary_support_edge_ids: [],
        semantic_uncertainty_rollup: "all_bottom_support_edges_uncertain",
        rq_boundary_rollup: "any_bottom_support_edge_crosses_rq_leaf_path",
        model_call_count: 0,
      },
      gray_zone_semantics_changed: false,
      model_call_count: 0,
    },
    source_algorithm: "membership_weighted_bottom_edge_projection",
    protocol_version: "membership_q15_layer_type_calibrated_v3",
    state_hash: CONTRACT_HASH,
    support_chunk_ids: ["chunk:source", "chunk:target"],
    support_chunk_edge_ids: [bottomEdgeId],
    support_mid_edge_ids: [],
    support_mid_concept_ids: [],
    support_rq_prefix_ids: ["rq:fixture"],
    metadata: {
      candidate_channels: [],
      top_alternative_prefix_ids: [],
      rq_path: [],
      support_chunk_ids_sample: [],
      support_chunk_edge_ids_sample: [],
    },
    ...overrides,
  };
}

export function makeProjectionGroupDiagnostics(
  overrides: Partial<GraphProjectionGroupDiagnostics> = {},
): GraphProjectionGroupDiagnostics {
  const emptyDistribution = { count: 0 };
  return {
    protocol_hashes: [],
    protocol_hash_edge_count: 0,
    protocol_hash_coverage: 0,
    protocol_hash_consistent: true,
    source_algorithm_coverage: 0,
    protocol_version_coverage: 0,
    state_hash_coverage: 0,
    full_edge_count: 0,
    supported_edge_count: 0,
    support_coverage: 0,
    raw_projected_distance_coverage: 0,
    calibrated_projected_distance_coverage: 0,
    raw_projected_strength_coverage: 0,
    raw_projected_distance_distribution: emptyDistribution,
    calibrated_projected_distance_distribution: emptyDistribution,
    raw_projected_strength_distribution: emptyDistribution,
    support_membership_mass_distribution: emptyDistribution,
    support_contribution_count_distribution: emptyDistribution,
    normalization_protocol_counts: {},
    normalization_stats_hashes: [],
    ...overrides,
  };
}

type GraphResponseOverrides = Omit<Partial<GraphResponse>, "counts"> & {
  counts?: Partial<GraphResponse["counts"]>;
};

export function makeGraphResponse(overrides: GraphResponseOverrides = {}): GraphResponse {
  const nodes = overrides.nodes ?? [];
  const edges = overrides.edges ?? [];
  return {
    contract_version: "four_layer_graph_public_v1",
    knowledge_base_id: "kb-contract-fixture",
    graph_type: "mid-concepts",
    schema_version: "context_graph_v1",
    view: "overview",
    nodes,
    edges,
    full_counts: overrides.full_counts ?? { nodes: nodes.length, edges: edges.length },
    sampled_counts: overrides.sampled_counts ?? { nodes: nodes.length, edges: edges.length },
    node_counts: overrides.node_counts ?? { sampled: nodes.length, full: nodes.length },
    edge_counts: overrides.edge_counts ?? { sampled: edges.length, full: edges.length },
    freshness: overrides.freshness ?? {
      is_stale: false,
      stale_reasons: [],
      canonical_state_validation_reasons: [],
      local_hint_protocol_version: "context_graph_freshness_v1",
    },
    hash: overrides.hash ?? CONTRACT_HASH,
    hashes: overrides.hashes ?? {
      local_hint_protocol_version: "context_graph_freshness_v1",
      runtime_settings_hash: CONTRACT_HASH,
      agent_operating_envelope_hash: CONTRACT_HASH,
    },
    stale_reason: overrides.stale_reason ?? null,
    grounding: overrides.grounding ?? {
      mid_grounded_rate: 1,
      mid_total: 0,
      coarse_grounded_rate: 1,
      coarse_total: 0,
    },
    retrieval_contribution: overrides.retrieval_contribution ?? {
      trace_count: 0,
      has_observations: false,
      frontier_pops: 0,
      dominance_pruned_count: 0,
      expanded_edge_contribution: {},
      convergence_reasons: {},
      scores_json_primary: false,
    },
    edge_distance_diagnostics: overrides.edge_distance_diagnostics ?? {
      applicable: false,
      reason: "not_applicable",
      protocol_hashes: [],
      by_edge_type: {},
    },
    projection_diagnostics: overrides.projection_diagnostics ?? {
      applicable: false,
      reason: "not_applicable",
    },
    diagnostics: overrides.diagnostics ?? {
      layer_full_counts: overrides.full_counts ?? { nodes: nodes.length, edges: edges.length },
      sampled_counts: overrides.sampled_counts ?? { nodes: nodes.length, edges: edges.length },
      layer_hash_key: "mid_concept_hash",
      layer_hash: overrides.hash ?? CONTRACT_HASH,
    },
    ...overrides,
    counts: { ...emptyCounts, ...overrides.counts },
  };
}

export function makeSupportRefs(overrides: Partial<RetrievalSupportRefs> = {}): RetrievalSupportRefs {
  return {
    edge_ids: [],
    edge_types: [],
    support_ids: [],
    support_chunk_ids: [],
    support_chunk_edge_ids: [],
    support_relation_edge_ids: [],
    support_rq_prefix_ids: [],
    support_rq_prefix_node_ids: [],
    support_mid_edge_ids: [],
    support_mid_concept_ids: [],
    entry_strengths: {},
    raw_entry_strengths: {},
    mid_concept_ids: [],
    rq_prefix_ids: [],
    chunk_candidate_sources: [],
    ...overrides,
  };
}

export function makeTraversalState(overrides: Partial<RetrievalTraversalState> = {}): RetrievalTraversalState {
  return {
    layer: "mid",
    node_id: "mid:fixture",
    path: [],
    path_edge_ids: [],
    path_edge_distances: [],
    path_edge_strengths: [],
    path_edge_types: [],
    covered_facets: [],
    evidence_roles: [],
    visit_counts: {},
    edge_reuse_counts: {},
    support_refs: makeSupportRefs(),
    entry_parent_refs: [],
    entry_support_refs: makeSupportRefs(),
    state_signature: {
      covered_facets: [],
      evidence_roles: [],
      path_edge_type_multiset: {},
    },
    cycle_distance_rewards: [],
    ...overrides,
  };
}

export function makeGrayBudgetState(
  overrides: Partial<GrayTraversalObservationBudgetState> = {},
): GrayTraversalObservationBudgetState {
  return {
    protocol_version: "traversal_observation_budget_v1",
    scope: "trace",
    limit: 16,
    local_rule_evaluation_index: 1,
    layer_local_rule_evaluation_index: 1,
    cadence_due: true,
    expanded_packet_requested: true,
    expanded_observation_count_before: 0,
    expanded_observation_count_after: 1,
    remaining_after: 15,
    observation_compacted: false,
    compaction_reason: null,
    hard_interrupt_applied: false,
    budget_exhausted_after: false,
    model_call_count: 0,
    ...overrides,
  };
}

export function makeGrayDecision(
  overrides: Partial<RetrievalGrayZoneDecision> = {},
): RetrievalGrayZoneDecision {
  return {
    layer: "mid",
    edge_id: "edge:gray",
    from_node_id: "mid:a",
    to_node_id: "mid:b",
    path_distance: 0.5,
    distance_zone: "gray",
    decision: "continue",
    decision_reason: "support_progress",
    protocol_version: "deterministic_support_progress_v1",
    protocol_hash: CONTRACT_HASH,
    input_hash: CONTRACT_HASH,
    threshold_hash: CONTRACT_HASH,
    traversal_protocol_hash: CONTRACT_HASH,
    runtime_settings_hash: CONTRACT_HASH,
    agent_operating_envelope_hash: CONTRACT_HASH,
    decision_hash: CONTRACT_HASH,
    matched_rule: "support_progress",
    predicates: {},
    minimum_audit: {
      current_layer: "mid",
      distance_zone: "gray",
      path_distance: 0.5,
      predicates: {},
      support_ids_after: [],
      thresholds: {},
    },
    observation: null,
    observation_compacted: false,
    hard_interrupt_state: { traversal_observation_budget: makeGrayBudgetState() },
    model_call_count: 0,
    decision_source: "deterministic_local_rule",
    support_progress: {},
    support_refs: makeSupportRefs(),
    covered_facets: [],
    semantic_uncertain_edge: false,
    crossing_rq_boundary: false,
    gray_candidate_reasons: [],
    ...overrides,
  };
}

export function makeRetrievalStep(
  overrides: Partial<GraphRetrievalStepResponse> = {},
): GraphRetrievalStepResponse {
  return {
    id: "step:fixture",
    step_index: 0,
    layer: "mid",
    action: "walk_graph_frontier",
    action_type: "walk_graph_frontier",
    input: {
      entry_node_ids: [],
      coarse_entry_ids: [],
      mid_entry_ids: [],
      rq_membership_entry_ids: [],
      query_rq_path: [],
      result_chunk_ids: [],
      hit_chunk_ids: [],
    },
    output: {
      accepted_node_ids: [],
      selected_node_ids: [],
      accepted_chunk_ids: [],
      source_span_count: 0,
    },
    candidate_pool_ids: [],
    selected_topk_ids: [],
    per_parent_budget_status: {},
    popped_frontier_state: makeTraversalState(),
    expanded_edge_ids: [],
    dominance_pruned_count: 0,
    cycle_distance_reward: 0,
    gray_zone_path_decisions: [],
    diagnostics: {
      retrieval_granularity: "mid",
      scores_json_retired_as_primary_audit: true,
    },
    ...overrides,
  };
}

export function makeTraceResponse(
  overrides: Partial<RetrievalTraceStepsResponse> = {},
): RetrievalTraceStepsResponse {
  return {
    contract_version: "layered_retrieval_trace_public_v1",
    trace_id: "trace:fixture",
    conversation_state_scope_hash: CONTRACT_HASH,
    concept_path: [],
    query_facets: {
      query: "fixture query",
      protocol_version: "query_facet_packet_v2",
      terms: [],
      required_facets: [],
      facet_groups: [],
      drop_terms: [],
      answer_shape: "factoid",
      intent: "lookup",
      diagnostics: {
        source: "deterministic",
        schema_validation: "canonical_facet_groups_only",
        query_facet_protocol_hash: CONTRACT_HASH,
        lexical_terms: [],
        dropped_query_terms: [],
        llm_keys: [],
      },
    },
    entry_nodes: [],
    stage_queues: {},
    candidate_pools: {
      mid_by_coarse: [],
      chunk_by_mid: [],
    },
    topk_selection: {},
    frontier: [],
    path_labels: [],
    node_contributions: [],
    convergence: {},
    trace_diagnostics: makeTraceDiagnostics(),
    rq_diagnostics: { query_rq_path: [] },
    gray_zone_protocol: "deterministic_support_progress_v1",
    gray_zone_model_call_count: 0,
    gray_zone_determinism: {
      status: "passed",
      checked_record_count: 0,
      unique_record_count: 0,
      local_rule_record_count: 0,
      red_partition_record_count: 0,
      hard_stop_partition_record_count: 0,
      duplicate_reference_count: 0,
      conflict_count: 0,
      incomplete_record_count: 0,
      conflicts: [],
      issues: [],
    },
    gray_zone_path_decisions: [],
    path_distance_threshold_hits: [],
    result_chunk_ids: [],
    steps: [],
    ...overrides,
  };
}

export function makeContextPackage(
  overrides: Partial<ContextPackageResponse> = {},
): ContextPackageResponse {
  return {
    contract_version: "context_package_public_v1",
    id: "package:fixture",
    knowledge_base_id: "kb-contract-fixture",
    package_hash: CONTRACT_HASH,
    package_hash_card: {
      protocol_version: "context_package_public_hash_v1",
      canonicalization: "json_utf8_sort_keys_compact_v1",
      hashed_public_fields: [
        "contract_version",
        "id",
        "retrieval_trace_id",
        "knowledge_base_id",
        "query",
        "hit_chunk_ids",
        "restored_chunk_ids",
        "bridge_chunk_ids",
        "parent_structure_node_ids",
        "concept_path",
        "graph_path_ids",
        "reached_by_paths",
        "node_contributions",
        "why_selected",
        "cycle_convergence_score",
        "dedupe_keys",
        "covered_facets",
        "package",
        "contexts",
        "token_budget",
        "token_count",
        "citation_spans",
        "graph_expansion_paths",
        "diagnostics",
      ],
      public_payload_hash: CONTRACT_HASH,
      public_citation_spans_hash: CONTRACT_HASH,
      citation_spans_consistency: "persisted_equals_public_projection",
      chunk_count: 0,
      citation_span_count: 0,
      graph_expansion_path_count: 0,
    },
    query: "fixture query",
    hit_chunk_ids: [],
    restored_chunk_ids: [],
    bridge_chunk_ids: [],
    parent_structure_node_ids: [],
    concept_path: [],
    graph_path_ids: [],
    reached_by_paths: [],
    node_contributions: [],
    why_selected: {},
    dedupe_keys: [],
    covered_facets: [],
    package: { contract_version: "context_package_chunks_v1", chunks: [] },
    contexts: [],
    token_budget: 1024,
    token_count: 0,
    citation_spans: [],
    graph_expansion_paths: [],
    diagnostics: {
      context_restoration_protocol: "structure_context_restore_v1",
      repair_gray_zone_model_call_count: 0,
      repair_gray_zone_decision_authority: false,
      retrieval_granularity: "mid",
      conversation_state_scope_hash: CONTRACT_HASH,
      conversation_state_is_evidence: false,
      runtime_settings_hash: CONTRACT_HASH,
      path_summary: {
        node_visit_count: 0,
        distinct_parent_count: 0,
        distinct_path_count: 0,
        distinct_edge_type_count: 0,
        covered_facets: [],
        support_chunk_union: [],
        reached_by_paths: [],
        cycle_convergence_score: 0,
      },
      dedupe_keys: [],
      restore_counts: {
        hit_chunks: 0,
        restored_chunks: 0,
        bridge_chunks: 0,
        graph_path_chunks: 0,
        parent_structure_nodes: 0,
        per_hit_chunk_budget: 0,
      },
      token_budget_audit: {
        token_budget: 1024,
        token_count: 0,
        within_budget: true,
        clipped_chunk_ids: [],
        skipped_chunk_ids: [],
        packing_protocol: "bounded_context_pack_v1",
      },
      snapshot_integrity: {
        protocol_version: "immutable_context_snapshot_v1",
        verified_document_version_count: 0,
        fail_closed: true,
      },
    },
    ...overrides,
  };
}
