from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
API_WORKDIR = "/app/apps/api"


def run_command(command: list[str], *, dry_run: bool = False) -> int:
    printable = " ".join(command)
    print(printable)
    if dry_run:
        return 0
    completed = subprocess.run(command, cwd=REPO_ROOT)
    return int(completed.returncode)


def docker_alembic(container: str, alembic_args: list[str]) -> list[str]:
    return ["docker", "exec", "-w", API_WORKDIR, container, "alembic", *alembic_args]


def build_command(args: argparse.Namespace) -> list[str]:
    if args.command == "current":
        return docker_alembic(args.container, ["current"])
    if args.command == "heads":
        return docker_alembic(args.container, ["heads"])
    if args.command == "upgrade":
        return docker_alembic(args.container, ["upgrade", args.revision])
    if args.command == "downgrade":
        return docker_alembic(args.container, ["downgrade", args.revision])
    if args.command == "check":
        return docker_alembic(args.container, ["check"])
    if args.command == "revision":
        revision_args = ["revision", "--autogenerate", "-m", args.message]
        if args.rev_id:
            revision_args.extend(["--rev-id", args.rev_id])
        return docker_alembic(args.container, revision_args)
    raise ValueError(f"Unsupported command: {args.command}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run Alembic safely inside the API Docker container.")
    parser.add_argument("--container", default="course-kg-api", help="API container name.")
    parser.add_argument("--dry-run", action="store_true", help="Print the docker command without executing it.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("current", help="Show the current database revision.")
    subparsers.add_parser("heads", help="Show migration heads in code.")
    subparsers.add_parser("check", help="Run alembic check inside the API container.")

    upgrade = subparsers.add_parser("upgrade", help="Upgrade the database revision.")
    upgrade.add_argument("revision", nargs="?", default="head")

    downgrade = subparsers.add_parser("downgrade", help="Downgrade the database revision.")
    downgrade.add_argument("revision", help="Target revision, for example -1.")

    revision = subparsers.add_parser("revision", help="Create an autogenerated migration revision.")
    revision.add_argument("-m", "--message", required=True)
    revision.add_argument("--rev-id", default="")

    args = parser.parse_args()
    command = build_command(args)
    return run_command(command, dry_run=args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
